[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coroutines = "1.10.2"
ksp = "2.3.4"
coreKtx = "1.17.0"
koin-bom = "4.1.1"
room = "2.8.4"
retrofit = "3.0.0"
moshi = "1.15.2"
coil = "3.3.0"
junit = "6.0.2"
junitVersion = "1.3.0"
mockk = "1.14.7"
turbine = "1.2.1"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"

[libraries]

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines"}
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines"}

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit"}

moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi"}
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi"}

coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil"}
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil"}

junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine"}
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
room = { id = "androidx.room", version.ref = "room"}

